### ISSUE TITLE
Serialization and deserialization of G2

### ISSUE THREAD

**Issue by ggq89** [lightec-xyz/bls-verify-gadget#3]
G2Projective does not implement serialization and deserialization methods of the form:
`{"x": "0x01a6ba2f9a11fa5598b2d8ace0fbe0a0eacb65deceb476fbbcb64fd24557c2f4b18ecfc5663e54ae16a84f5ab7f62534,0x11fca2ff525572795a801eed17eb12785887c7b63fb77a42be46ce4a34131d71f7a73e95fee3f812aea3de78b4d01569", "y": "0x0b6798718c8aed24bc19cb27f866f1c9effcdbf92397ad6448b5c9db90d2b9da6cbabf48adc1adf59a1a28344e79d57e,0x03a47f8e6d1763ba0cad63d6114c0accbef65707825a511b251a660a9b3994249ae4e63fac38b23da0c398689ee2ab52"}`

**Comment by readygo67** [comment]
this feature has been implemented.

**Comment by readygo67** [comment]
this feature has been implemented.
