### ISSUE TITLE
Not processing public key is 0

### ISSUE THREAD

**Issue by ggq89** [lightec-xyz/bls-verify-gadget#4]
When deserializing a public key, an input of the form below should not be converted into a valid public key:
`"0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"`

**Comment by readygo67** [comment]
In current implementation， we don't detect all "0x000" pubic key. In real,  all "0x0" public is not allowed.

**Comment by ggq89** [comment]
The most important thing is that the 0 public key cannot be used for signature verification.
