### ISSUE TITLE
A panic occurs when deserializing an invalid signature

### ISSUE THREAD

**Issue by ggq89** [lightec-xyz/bls-verify-gadget#5]
A panic occurs when deserializing an invalid signature like this:
`0xae82747ddeefe4fd64cf9cedb9b04ae3e8a43420cd255e3c7cd06a8d88b7c7f8638543719981c5d16fa3527c468c25f0026704a6951bde891360c7e8d12ddee0559004ccdbe6046b55bae1b257ee97f7cdb955773d7cf29adf3ccbb9ffffffff`

**Comment by readygo67** [comment]
change "from" to "try_from" to cover such error
